Replace PTZ boolean normalization with boolean constraints
w3c/mediacapture-image pull request #271
Opened 2020-11-04 23:21 UTC by eehakkin

This along with https://github.com/w3c/mediacapture-main/pull/742 is to clarify meaning of PTZ constraints presence (see #256).

2020-11-12 14:49 UTC, beaufortfrancois commented
@jan-ivar @guidou @youennf Does this look good to you?

2021-01-15 01:47 UTC, jan-ivar requested changes
Logic seems sound, but once w3c/mediacapture-main#766 is merged, I'm hoping we can reduce the prose even more. PTAL

2021-01-15 01:47 UTC, jan-ivar commented on index.bs
> +    This boolean constraint is satisfied by a <a>settings dictionary</a> if the constraint value matches the existence of the numeric pan setting in the settings dictionary.
The _constrainable property_ is never a boolean, only the constraint. Once https://github.com/w3c/mediacapture-main/pull/766 is merged, we can say:
```suggestion
    Constraints on pan influence camera selection through {{fitness distance}} toward cameras with the ability to pan. To exert this influence without overwriting the current pan setting, pan may be constrained to true. Conversely, constraining it to false disfavors cameras with the ability to pan.
```

2021-01-15 01:47 UTC, jan-ivar commented on index.bs
> +    This boolean constraint is satisfied by a <a>settings dictionary</a> if the constraint value matches the existence of the numeric tilt setting in the settings dictionary.
adding "with a value other than false" and a comma
```suggestion
    Constraints on tilt influence camera selection through {{fitness distance}} toward cameras with the ability to tilt. To exert this influence without overwriting the current tilt setting, tilt may be constrained to true. Conversely, constraining it to false disfavors cameras with the ability to tilt.
```

2021-01-15 01:47 UTC, jan-ivar commented on index.bs
> +    This boolean constraint is satisfied by a <a>settings dictionary</a> if the constraint value matches the existence of the numeric zoom setting in the settings dictionary.
```suggestion
    Constraints on zoom influence camera selection through {{fitness distance}} toward cameras with the ability to zoom. To exert this influence without overwriting the current zoom setting, zoom may be constrained to true. Conversely, constraining it to false disfavors cameras with the ability to zoom.
```

2021-01-15 01:47 UTC, jan-ivar commented on index.bs
> +    Any algorithm which uses a {{MediaTrackConstraintSet}} object whose {{MediaTrackConstraintSet/pan}} dictionary member exists MUST either <a>request permission to use</a> (as defined in [[!permiss
```suggestion
    Any algorithm which uses a {{MediaTrackConstraintSet}} object whose {{MediaTrackConstraintSet/pan}} dictionary member exists with a value other than false MUST either <a>request permission to use</a> (as defined in [[!permissions]]) a PermissionDescriptor with its name member set to {{PermissionName/camera}} and its {{CameraDevicePermissionDescriptor/panTiltZoom}} member set to true, and, optionally, consider its {{DevicePermissionDescriptor/deviceId}} member set to any appropriate device's deviceId, or decide not to expose the pan setting.
```

2021-01-15 01:47 UTC, jan-ivar commented on index.bs
> +    Any algorithm which uses a {{MediaTrackConstraintSet}} object whose {{MediaTrackConstraintSet/tilt}} dictionary member exists MUST either <a>request permission to use</a> (as defined in [[!permis
```suggestion
    Any algorithm which uses a {{MediaTrackConstraintSet}} object whose {{MediaTrackConstraintSet/tilt}} dictionary member exists with a value other than false MUST either <a>request permission to use</a> (as defined in [[!permissions]]) a PermissionDescriptor with its name member set to {{PermissionName/camera}} and its {{CameraDevicePermissionDescriptor/panTiltZoom}} member set to true, and, optionally, consider its {{DevicePermissionDescriptor/deviceId}} member set to any appropriate device's deviceId, or decide not to expose the tilt setting.
```

2021-01-15 01:47 UTC, jan-ivar commented on index.bs
> +    Any algorithm which uses a {{MediaTrackConstraintSet}} object whose {{MediaTrackConstraintSet/zoom}} dictionary member exists MUST either <a>request permission to use</a> (as defined in [[!permis
```suggestion
    Any algorithm which uses a {{MediaTrackConstraintSet}} object whose {{MediaTrackConstraintSet/zoom}} dictionary member exists with a value other than false MUST either <a>request permission to use</a> (as defined in [[!permissions]]) a PermissionDescriptor with its name member set to {{PermissionName/camera}} and its {{CameraDevicePermissionDescriptor/panTiltZoom}} member set to true, and, optionally, consider its {{DevicePermissionDescriptor/deviceId}} member set to any appropriate device's deviceId, or decide not to expose the zoom setting.
```

2021-03-15 17:29 UTC, jan-ivar commented
We should get this PR in before wide review of image capture starts, since it takes advantage of stuff we merged in https://github.com/w3c/mediacapture-main/pull/766.

To that end, I'll commit my suggestions above to this PR and solicit reviews.

2021-03-15 17:38 UTC, jan-ivar reviewed
s/after a possible normalization/with a value other than false/

2021-03-15 17:38 UTC, jan-ivar commented on index.bs
> +    If the {{visibilityState}} of the <a>top-level browsing context</a> value is "hidden", the {{applyConstraints()}} algorithm MUST throw a {{SecurityError}} if {{MediaTrackConstraintSet/pan}} dicti
```suggestion
    If the {{visibilityState}} of the <a>top-level browsing context</a> value is "hidden", the {{applyConstraints()}} algorithm MUST throw a {{SecurityError}} if {{MediaTrackConstraintSet/pan}} dictionary member exists with a value other than false.</li>
```

2021-03-15 17:38 UTC, jan-ivar commented on index.bs
>      If the {{visibilityState}} of the <a>top-level browsing context</a> value is "hidden", the {{applyConstraints()}} algorithm MUST throw a {{SecurityError}} if {{MediaTrackConstraintSet/tilt}} dict
```suggestion
    If the {{visibilityState}} of the <a>top-level browsing context</a> value is "hidden", the {{applyConstraints()}} algorithm MUST throw a {{SecurityError}} if {{MediaTrackConstraintSet/tilt}} dictionary member exists with a value other than false.
```

2021-03-15 17:38 UTC, jan-ivar commented on index.bs
> +    If the {{visibilityState}} of the <a>top-level browsing context</a> value is "hidden", the {{applyConstraints()}} algorithm MUST throw a {{SecurityError}} if {{MediaTrackConstraintSet/zoom}} dict
```suggestion
    If the {{visibilityState}} of the <a>top-level browsing context</a> value is "hidden", the {{applyConstraints()}} algorithm MUST throw a {{SecurityError}} if {{MediaTrackConstraintSet/zoom}} dictionary member exists with a value other than false.</li>
```

2021-03-15 17:58 UTC, jan-ivar commented
@riju @youennf PTAL.

TL;DR: We no longer need to normalize away boolean inputs to non-boolean constraints as they're handled in [fitness distance](https://w3c.github.io/mediacapture-main/getusermedia.html#dfn-fitness-distance): _"4. If constraintValue is a boolean, but the constrainable property is not, then the fitness distance is based on whether the settings dictionary's constraintName member exists or not, from the formula `(constraintValue == exists) ? 0 : 1`"_

2021-03-17 14:11 UTC, riju approved these changes
Thanks @eehakkin, I think all of @jan-ivar 's requested changed are now handled.

2021-03-18 09:08 UTC, eehakkin commented
Thanks @jan-ivar. As a final touch, I replaced occurrences of `{{fitness distance}}` with `<a>fitness distance</a>` so that links work properly.

2021-03-29 15:38 UTC, merged